//
//  TriggerEventType.h
//  SohaPlayer
//
//  Created by Hưng Nguyễn Thạc on 11/20/18.
//  Copyright © 2018 Hung Nguyen. All rights reserved.
//

static NSString* USER_SEEK = @"USER_SEEK",
*USER_CHANGE_VOLUME = @"USER_CHANGE_VOLUME",
*USER_CHANGE_MUTE = @"USER_CHANGE_MUTE",
*USER_REPLAY_CONTENT = @"USER_REPLAY_CONTENT",
*USER_SCRUBBING_PROGRESS = @"USER_SCRUBBING_PROGRESS",
*USER_PAN_PROGRESS = @"USER_PAN_PROGRESS",
*USER_PAN_VOLUME = @"USER_PAN_VOLUME",

*USER_PAUSE = @"USER_PAUSE",
*USER_RESUME = @"USER_RESUME",

*USER_SKIP_AD = @"USER_SKIP_AD",

*TRACKING_VOLUME =@"TRACKING_VOLUME",

*PLAYER_ENDED_CONTEND = @"PLAYER_ENDED_CONTEND",
*PLAYER_REPLAY_CONTEND = @"PLAYER_REPLAY_CONTEND",
*PLAYER_ERROR = @"PLAYER_ERROR",
*PLAYER_READY =@"PLAYER_READY",

*PLAYER_REQUEST_QUALITY_INFO = @"PLAYER_REQUEST_QUALITY_INFO",

*AD_ORDER_START_MIDROLL = @"AD_ORDER_START_MIDROLL",
*AD_ORDER_START_POSTROLL = @"AD_ORDER_START_POSTROLL",

*AD_START = @"AD_START", // trigger khi ad init
*AD_PLAY = @"AD_PLAY", // trigger khi lấy được vast response và gọi playAd
*AD_END = @"AD_END",
*AD_PAUSE_AD = @"AD_PAUSE_AD",
*AD_RESUME_AD = @"AD_RESUME_AD",
*AD_CANCEL = @"AD_CANCEL",
*AD_SKIP = @"AD_SKIP",
*AD_ENDED_POSTROLL = @"AD_ENDED_POSTROLL",
*AD_RESTORED_PLAYBACK = @"AD_RESTORED_PLAYBACK", // trigger khi đã set lại source của video chính
*AD_MIDROLL_VASTRESPONSE = @"AD_MIDROLL_VASTRESPONSE", // trigger khi lấy đc vast response khi chạy midroll
*AD_VASTRESPONSE = @"AD_VASTRESPONSE", // trigger khi lấy đc vast response và chuẩn bị chạy ad
// Vast event
*VAST_AD_VIDEO_START = @"VAST_AD_VIDEO_START",
*VAST_AD_START = @"VAST_AD_START",
*VAST_AD_CLICK_THRU = @"VAST_AD_CLICK_THRU",
*VAST_AD_VIDEO_SHOW = @"VAST_AD_VIDEO_SHOW",
// Vpaid event
*VPAID_AD_START = @"VPAID_AD_START",

*VPAID_PAUSE_AD = @"VPAID_PAUSE_AD",
*VPAID_RESUME_AD = @"VPAID_RESUME_AD",
// Các event được listen từ adUnit sau đó trigger
*VPAID_AD_SKIPPED = @"VPAID_AD_SKIPPED",
*VPAID_AD_STARTED = @"VPAID_AD_STARTED",
*VPAID_AD_STOPPED = @"VPAID_AD_STOPPED",
*VPAID_AD_IMPRESSION = @"VPAID_AD_IMPRESSION",
*VPAID_AD_PLAYING = @"VPAID_AD_PLAYING",
*VPAID_AD_PAUSED = @"VPAID_AD_PAUSED",

*VPAID_AD_VIDEO_START = @"VPAID_AD_VIDEO_START",
*VPAID_AD_VIDEO_FIRST_QUARTILE = @"VPAID_AD_VIDEO_FIRST_QUARTILE",
*VPAID_AD_VIDEO_MID_POINT = @"VPAID_AD_VIDEO_MID_POINT",
*VPAID_AD_VIDEO_THIRD_QUARTILE = @"VPAID_AD_VIDEO_MID_POINT",
*VPAID_AD_VIDEO_COMPLETE = @"VPAID_AD_VIDEO_COMPLETE",

*VPAID_AD_VOLUME_CHANGE = @"VPAID_AD_VOLUME_CHANGE",

*VPAID_AD_CLICK_THRU = @"VPAID_AD_CLICK_THRU",
*VPAID_AD_USER_ACCEPT_INVITATION = @"VPAID_AD_USER_ACCEPT_INVITATION",
*VPAID_AD_USER_CLOSE = @"VPAID_AD_USER_CLOSE",
*VPAID_AD_USER_MINIMIZE = @"VPAID_AD_USER_MINIMIZE",

*VPAID_AD_ERROR = @"VPAID_AD_ERROR",

*IMA_AD_START = @"IMA_AD_START",
*IMA_AD_SKIPPED = @"IMA_AD_SKIPPED",
*IMA_AD_STARTED = @"IMA_AD_STARTED",
*IMA_AD_STOPPED = @"IMA_AD_STOPPED",
*IMA_AD_IMPRESSION = @"IMA_AD_IMPRESSION",
*IMA_AD_PLAYING = @"IMA_AD_PLAYING",
*IMA_AD_PAUSED = @"IMA_AD_PAUSED",
*IMA_AD_LOADED = @"IMA_AD_LOADED",
*IMA_AD_COMPLETE = @"IMA_AD_COMPLETE",
*IMA_ALL_ADS_COMPLETED = @"IMA_ALL_ADS_COMPLETED",
*IMA_FIRST_QUARTILE = @"IMA_FIRST_QUARTILE",
*IMA_MIDPOINT = @"IMA_MIDPOINT",
*IMA_THIRD_QUARTILE = @"IMA_THIRD_QUARTILE",
*IMA_TAPPED = @"IMA_TAPPED",
*IMA_CLICKED = @"IMA_CLICKED",
*IMA_UNKNOWN = @"IMA_UNKNOWN",
*PLAYER_FILLING_VOLUME = @"PLAYER_FILLING_VOLUME";
